# Site settings
title: ci4energy
email: paul.kaufmann@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    The main goal of this task force is to promote the research on Computational Intelligence methods for their application to the energy production and consumption domain.
baseurl: ""
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: paul-kaufmann

# Build settings
markdown: kramdown
